"""add_project_context_fields

Revision ID: 96e6d1121bf5
Revises: a1c3e5d7f9b2
Create Date: 2026-02-23 09:52:12.235628

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '96e6d1121bf5'
down_revision = 'a1c3e5d7f9b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_events_event_type_created_at'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_task_comment_task_id_created_at'), table_name='activity_events', postgresql_where="((event_type)::text = 'task.comment'::text)")
    op.drop_index(op.f('ix_board_memory_board_id_is_chat_created_at'), table_name='board_memory')
    op.drop_index(op.f('ix_board_webhook_payloads_board_webhook_received_at'), table_name='board_webhook_payloads')
    op.add_column('boards', sa.Column('project_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('boards', sa.Column('claude_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('boards', sa.Column('gemini_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('gateway_installed_skills_gateway_id_fkey'), 'gateway_installed_skills', type_='foreignkey')
    op.create_foreign_key(None, 'gateway_installed_skills', 'gateways', ['gateway_id'], ['id'])
    op.drop_index(op.f('ix_tasks_board_id_assigned_agent_id_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_board_id_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_board_id_status_created_at'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_board_id_status_created_at'), 'tasks', ['board_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_board_id_created_at'), 'tasks', ['board_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_board_id_assigned_agent_id_created_at'), 'tasks', ['board_id', 'assigned_agent_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'gateway_installed_skills', type_='foreignkey')
    op.create_foreign_key(op.f('gateway_installed_skills_gateway_id_fkey'), 'gateway_installed_skills', 'gateways', ['gateway_id'], ['id'], ondelete='CASCADE')
    op.drop_column('boards', 'gemini_context')
    op.drop_column('boards', 'claude_context')
    op.drop_column('boards', 'project_context')
    op.create_index(op.f('ix_board_webhook_payloads_board_webhook_received_at'), 'board_webhook_payloads', ['board_id', 'webhook_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_board_memory_board_id_is_chat_created_at'), 'board_memory', ['board_id', 'is_chat', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_events_task_comment_task_id_created_at'), 'activity_events', ['task_id', 'created_at'], unique=False, postgresql_where="((event_type)::text = 'task.comment'::text)")
    op.create_index(op.f('ix_activity_events_event_type_created_at'), 'activity_events', ['event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###
