"""add context fields to board_groups

Revision ID: fbc9e606f4c1
Revises: 157fd665d7a0
Create Date: 2026-02-23 12:55:38.189999

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc9e606f4c1'
down_revision = '157fd665d7a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_groups', sa.Column('project_context', sa.Text(), nullable=True))
    op.add_column('board_groups', sa.Column('claude_context', sa.Text(), nullable=True))
    op.add_column('board_groups', sa.Column('gemini_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board_groups', 'gemini_context')
    op.drop_column('board_groups', 'claude_context')
    op.drop_column('board_groups', 'project_context')
    # ### end Alembic commands ###
